#!/usr/bin/env python3
"""Emit a linker-script-syntax file declaring every func_<addr> / D_<addr>
symbol that is referenced by splat's .s output but is not yet defined.

Why this exists: splat's auto-symbols files (undefined_funcs_auto.us.txt,
undefined_syms_auto.us.txt) cover symbols whose addresses fall inside the
analyzed segments. References to addresses outside the main code range —
which arise when spimdisasm mis-identifies a literal data word as a code
pointer (e.g. `lui $reg, 0x82` ... `addiu $reg, $reg, 0x10` produces a
synthetic 'func_82000010' that is never actually called) — get emitted
into the asm but not into any auto-symbols file. Without resolving them
the linker fails, so we declare them as absolute addresses. They are
never executed; their only job is to make ld happy.

Output:  config/undefined_funcs_extra.us.txt  (regenerated from scratch)
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASM_DIR = ROOT / "asm"
SRC_DIR = ROOT / "src"
OUT = ROOT / "config" / "undefined_funcs_extra.us.txt"
EXISTING = [
    ROOT / "config" / "undefined_funcs_auto.us.txt",
    ROOT / "config" / "undefined_syms_auto.us.txt",
    ROOT / "config" / "symbol_addrs.us.txt",
]

REF_RE = re.compile(r"\b(func_|D_)([0-9A-Fa-f]{4,8})\b")
DEFINED_RE = re.compile(r"^\s*(func_|D_)([0-9A-Fa-f]{4,8})\s*=\s*0x", re.M)
GLABEL_RE = re.compile(r"^\s*(?:glabel|alabel|jlabel|dlabel)\s+(func_|D_)([0-9A-Fa-f]{4,8})", re.M)
# Match a definition in a C source file: any (func_|D_)NAME followed by ( or = or [ or ;
C_DEF_RE = re.compile(r"\b(func_|D_)([0-9A-Fa-f]{4,8})\b\s*[(\[=;]", re.M)


def collect_defined() -> set[str]:
    defined: set[str] = set()
    for p in EXISTING:
        if not p.is_file():
            continue
        for m in DEFINED_RE.finditer(p.read_text(errors="replace")):
            defined.add(f"{m.group(1)}{m.group(2).upper()}")
    if SRC_DIR.is_dir():
        for c in SRC_DIR.rglob("*.c"):
            try:
                text = c.read_text(errors="replace")
            except OSError:
                continue
            # Only treat lines that are NOT extern declarations and NOT
            # plain references (RHS of assignment, args to a call) as
            # definitions. A real C definition has the symbol preceded
            # by a type/qualifier on the same line — never `extern`,
            # never as the RHS of `=`, `,`, `(`, etc.
            for line in text.splitlines():
                if "extern" in line:
                    continue
                for m in C_DEF_RE.finditer(line):
                    # Reject if the char immediately before the name (after
                    # trimming whitespace) is one of `= , ( ;`, since that
                    # marks usage rather than definition.
                    pre = line[: m.start()].rstrip()
                    if pre and pre[-1] in "=,(;":
                        continue
                    defined.add(f"{m.group(1)}{m.group(2).upper()}")
    return defined


def main() -> int:
    defined = collect_defined()
    referenced: dict[str, str] = {}     # name -> address-as-hex (no 0x prefix)

    for s in ASM_DIR.rglob("*.s"):
        if "nonmatchings" in s.parts:
            continue
        try:
            text = s.read_text(errors="replace")
        except OSError:
            continue
        # Don't re-export local labels declared within this file.
        local = {f"{m.group(1)}{m.group(2).upper()}" for m in GLABEL_RE.finditer(text)}
        for m in REF_RE.finditer(text):
            name = f"{m.group(1)}{m.group(2).upper()}"
            if name in defined or name in local:
                continue
            # Use the captured hex as the address. Pad to 32 bits.
            addr = m.group(2).upper().zfill(8)
            referenced.setdefault(name, addr)

    # Also scan C sources: a function pointer like func_80006E24 may be
    # referenced only from C (e.g. as a callback assigned to a global) and
    # never appear in any .s file. Without this scan the linker fails to
    # resolve such symbols.
    if SRC_DIR.is_dir():
        for c in SRC_DIR.rglob("*.c"):
            try:
                text = c.read_text(errors="replace")
            except OSError:
                continue
            for m in REF_RE.finditer(text):
                name = f"{m.group(1)}{m.group(2).upper()}"
                if name in defined:
                    continue
                addr = m.group(2).upper().zfill(8)
                referenced.setdefault(name, addr)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w") as f:
        f.write("/* Auto-generated by tools/gen_symbols_from_asm.py — do not edit by hand. */\n")
        f.write("/* Defines symbols referenced from asm/ that splat's auto-files missed. */\n")
        f.write("/* Most are likely spimdisasm false-positive code pointers; defining     */\n")
        f.write("/* them as absolute addresses lets the round-trip link complete.         */\n")
        for name in sorted(referenced):
            addr = referenced[name]
            f.write(f"{name} = 0x{addr};\n")

    print(f"gen_symbols_from_asm: wrote {len(referenced)} symbol(s) to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
