#!/usr/bin/env python3
"""Post-process splat-generated .s files for binutils strictness.

Modern GNU as (binutils >= 2.36) refuses to encode certain MIPS pseudo-
patterns that DO appear in real retail ROMs and therefore must be
reproduced exactly. We rewrite those lines into raw `.word 0xNNNNNNNN`
using the byte encoding that spimdisasm already prints in its leading
'/* romoff vram bytes */' comment.

The .s files are gitignored — they are regenerated by splat on every
'make split' — so this rewrite is a build-time fixup, not a tracked
change. Run via the Makefile's split rule.

Currently handled patterns:
    bltzal $ra, <label>     # GAS rejects: source must not be $31

Add new patterns to PATTERNS as they are discovered. Each pattern is
keyed by a regex that captures the spimdisasm comment AND the offending
mnemonic; the replacement uses only the comment's bytes hex group.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASM_DIR = ROOT / "asm"

# A spimdisasm instruction line looks like:
#   /* <romoff> <vram> <bytes> */  <mnemonic>  <operands>
# We capture the comment block and the bytes (group 'b'), then accept any
# of the offending instruction patterns after it.
COMMENT = r"(?P<lead>\s*/\*\s+\S+\s+\S+\s+(?P<b>[0-9A-Fa-f]{8})\s+\*/\s+)"
PATTERNS: list[re.Pattern[str]] = [
    re.compile(COMMENT + r"bltzal\s+\$ra\s*,\s*\S+\s*$"),
]


def fix_file(path: Path) -> int:
    try:
        text = path.read_text()
    except OSError:
        return 0
    out_lines = []
    n_fixed = 0
    for line in text.splitlines(keepends=True):
        replaced = False
        for pat in PATTERNS:
            m = pat.match(line)
            if m:
                out_lines.append(f"{m.group('lead')}.word 0x{m.group('b').upper()}\n")
                n_fixed += 1
                replaced = True
                break
        if not replaced:
            out_lines.append(line)
    if n_fixed:
        path.write_text("".join(out_lines))
    return n_fixed


def main() -> int:
    total = 0
    files_touched = 0
    for p in sorted(ASM_DIR.rglob("*.s")):
        if "nonmatchings" in p.parts:
            continue
        n = fix_file(p)
        if n:
            files_touched += 1
            total += n
    print(f"postprocess_asm: rewrote {total} line(s) across {files_touched} file(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
