#!/usr/bin/env python3
"""Progress reporter.

Counts bytes of code that are matched (built from C in src/) vs. still in
asm form, and updates docs/PROGRESS.md and the README status table. Reads
only build artifacts and the splat manifest — does not embed ROM bytes.

Modes:
    --update           rewrite docs/PROGRESS.md and README.md tables
    --list-unmatched   print a function-level list of remaining work
    (default)          print a one-line summary

This is a deliberately small, dependency-light implementation; it expects
the build to have run at least through 'make split'. If asm/ is empty (no
splat config yet), it reports zeros without erroring — the project is
designed to start with no progress and grow.
"""
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
PROGRESS_MD = ROOT / "docs" / "PROGRESS.md"
ASM_DIR = ROOT / "asm"
SRC_DIR = ROOT / "src"
BUILD_DIR = ROOT / "build"
CONFIG_DIR = ROOT / "config"


@dataclass
class Stats:
    matched_bytes: int = 0
    asm_bytes: int = 0
    asset_bytes: int = 0

    @property
    def total_code(self) -> int:
        return self.matched_bytes + self.asm_bytes

    def pct(self, n: int) -> float:
        return (100.0 * n / self.total_code) if self.total_code else 0.0


def collect_stats(version: str = "us") -> Stats:
    """Add up code/asset bytes from the most recently completed build.

    The numbers come from build/ artifacts (which are derived from the
    user's local ROM), never from the ROM directly and never embedded in
    this repository.
    """
    s = Stats()

    # Asm bytes: sum of '.s' files generated by splat.
    if ASM_DIR.is_dir():
        for p in ASM_DIR.rglob("*.s"):
            # Skip our hand-tracked nonmatchings — those are draft scaffolds,
            # not split-from-ROM asm, and counting them would double-count
            # against matched code.
            if "nonmatchings" in p.parts:
                continue
            s.asm_bytes += _count_asm_text_bytes(p)

    # Matched bytes: sum of '.text' size of every object in build/ whose
    # source is in src/. Falls back to 0 if no build has happened.
    if BUILD_DIR.is_dir():
        for p in BUILD_DIR.rglob("*.o"):
            rel = p.relative_to(BUILD_DIR)
            # The build mirrors src/'s structure into build/.
            src_candidate = SRC_DIR / rel.with_suffix(".c")
            if src_candidate.is_file():
                s.matched_bytes += _text_section_size(p)

    # Assets: total size of files extracted under assets/.
    asset_root = ROOT / "assets"
    if asset_root.is_dir():
        for p in asset_root.rglob("*"):
            if p.is_file() and p.name not in (".gitkeep",) and p.suffix != ".md":
                s.asset_bytes += p.stat().st_size

    return s


def _count_asm_text_bytes(path: Path) -> int:
    """Heuristic byte-count for a splat-emitted .s file: 4 bytes per
    instruction-looking line. Splat emits one mnemonic per line, so this
    is accurate enough for progress tracking without parsing.
    """
    n = 0
    insn_re = re.compile(r"^\s*\.?[A-Za-z]")  # crude: lines starting with a word
    skip_re = re.compile(r"^\s*(#|/\*|\*/|\.section|\.set|\.align|\.size|\.type|\.globl|\.weak|\.byte|\.half|\.word|\.ascii|\.asciz|\.space|glabel|jlabel|dlabel)")
    try:
        with path.open("r", errors="replace") as f:
            for line in f:
                if skip_re.match(line):
                    continue
                if insn_re.match(line):
                    n += 4
    except OSError:
        return 0
    return n


def _text_section_size(obj: Path) -> int:
    """Best-effort .text size from an ELF object. Falls back to file size
    if pyelftools isn't available."""
    try:
        from elftools.elf.elffile import ELFFile  # type: ignore
        with obj.open("rb") as f:
            elf = ELFFile(f)
            sec = elf.get_section_by_name(".text")
            return sec["sh_size"] if sec else 0
    except Exception:
        try:
            return obj.stat().st_size
        except OSError:
            return 0


# ---- README / PROGRESS.md rewriting -----------------------------------------

_README_TABLE_RE = re.compile(
    r"(\| Version[^\n]*\n\|[-:\s|]+\n)(\|[^\n]+\n)+",
    re.MULTILINE,
)
_PROGRESS_TABLE_RE = re.compile(
    r"(## Current status[^\n]*\n\n)(\|[^\n]+\n){3,}",
    re.MULTILINE,
)


def render_readme_row(s: Stats, version: str) -> str:
    label = {"us": "US 1.0", "eu": "EU 1.0", "jp": "JP 1.0"}.get(version, version)
    return (f"| {label:<10} | {s.pct(s.matched_bytes):24.2f}% | "
            f"{s.pct(s.asm_bytes):8.2f}% | "
            f"{s.pct(s.asset_bytes):15.2f}% |\n")


def update_readme(s: Stats, version: str) -> None:
    if not README.is_file():
        return
    text = README.read_text()
    header = ("| Version    | Decompiled (matched code) | Asm split | Assets extracted |\n"
              "|------------|--------------------------:|----------:|-----------------:|\n")
    new_table = header + render_readme_row(s, version)
    new_text, n = _README_TABLE_RE.subn(new_table, text, count=1)
    if n:
        README.write_text(new_text)


def update_progress_md(s: Stats, version: str) -> None:
    if not PROGRESS_MD.is_file():
        return
    text = PROGRESS_MD.read_text()
    table = (
        "## Current status (US 1.0)\n\n"
        "| Metric              | Bytes |    % |\n"
        "|---------------------|------:|-----:|\n"
        f"| Decompiled (matched)| {s.matched_bytes:>5} | {s.pct(s.matched_bytes):4.2f} |\n"
        f"| Asm split           | {s.asm_bytes:>5} | {s.pct(s.asm_bytes):4.2f} |\n"
        f"| Assets extracted    | {s.asset_bytes:>5} | --   |\n\n"
    )
    new_text, n = re.subn(
        r"## Current status \(US 1\.0\)\n\n(\|[^\n]+\n){5}\n",
        table,
        text,
        count=1,
    )
    if n:
        PROGRESS_MD.write_text(new_text)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--update", action="store_true",
                    help="rewrite README.md and docs/PROGRESS.md tables")
    ap.add_argument("--list-unmatched", action="store_true",
                    help="print one line per remaining asm function")
    ap.add_argument("--version", default="us")
    args = ap.parse_args()

    s = collect_stats(args.version)

    if args.list_unmatched:
        if not ASM_DIR.is_dir():
            return 0
        for p in sorted(ASM_DIR.rglob("*.s")):
            if "nonmatchings" in p.parts:
                continue
            print(p.relative_to(ROOT))
        return 0

    if args.update:
        update_readme(s, args.version)
        update_progress_md(s, args.version)

    print(f"matched={s.matched_bytes}B "
          f"asm={s.asm_bytes}B "
          f"assets={s.asset_bytes}B "
          f"matched%={s.pct(s.matched_bytes):.2f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
